<?php
// BookKeeper expense account names for 'Other...' typeahead search
// Auto-generated from DISHNET_AFRICA_LTD_2022.db — 236 accounts used 2+ times since 2023
// v4.9.10
return [
    '4G Telecom Ltd (Creditors)',
    'AFRINIC Ltd',
    'Administrative Annual Fee - NCA',
    'Advance For City Mall Office - Dishnet/4G',
    'Advance Rent for Tomping Branch Office',
    'Advance Rent for Tower At GMSH',
    'Advance Rent for UAP Tower',
    'Advance for Expense (Loan & Advance)',
    'Advance for House Rent - Dishnet Guest House',
    'Advances Taken - BlueCard',
    'Advances Taken - DishNet 4G',
    'Advertisement expenses',
    'Ahmed Commission - ICAP',
    'Arne Saw Commission - China North',
    'Audit Fees',
    'BBC (BHARATBHAI CHAUHAN ) - Unsecured Loan',
    'BPT Tax (Business Profit Tax) Tax Payable',
    'Bank Charges',
    'Bentley Walker - Material A/c',
    'Bentley Walker Ltd',
    'Bhavin Madlani Capital a/c',
    'Bimot Enterprises',
    'Bonus Payable To Modi Mawa Francis',
    'Bonus Payable to Amos',
    'Bonus Payable to Atul',
    'Bonus Payable to Bhavin',
    'Bonus Payable to Bidali',
    'Bonus Payable to Charles',
    'Bonus Payable to Dikko',
    'Bonus Payable to Emmanuel',
    'Bonus Payable to John Ochiti',
    'Bonus Payable to Kammanda',
    'Bonus Payable to Kennedy',
    'Bonus Payable to Margret 1',
    'Bonus Payable to Margret 2',
    'Bonus Payable to Mumma Marry',
    'Bonus Payable to Mumma Rose',
    'Bonus Payable to Nirav',
    'Bonus Payable to Paji (Shamshare Singh)',
    'Bonus Payable to Rupesh',
    'Bonus Payable to Yash',
    'Bonus payable to Mackline Anena',
    'Build Africa - Loan A/c (Loan & Advance)',
    'Build Africa Co Ltd - Against Luri Project - Creditor',
    'CVL General Supply (SS) Ltd - Cr',
    'Charles Commission - Afenet',
    'Chesco Hi-Tech General trading Ltd co.',
    'Christine Commission',
    'Clement Bazia Commission - NPSS',
    'Commission - NID Bank',
    'Construction in Progress - Plot No.291 & 292',
    'Custom Clearance Exps',
    'David - Custom Agent ( Loan & Advance )',
    'Deposit from client for Wi Fi device',
    'Digital Trend Mauritius / WILKEN AFRICA LTD',
    'Discount On Sale',
    'Discover Wings Tour and Travel Ltd',
    'DishNet SS A/c',
    'EXCHANGE USD TO SSP',
    'Electricity Expenses (Home/Office)',
    'Emerngency Fund ( Staff Welfare )',
    'Emmanuel Alli Luka Yaka Commission - AFENET',
    'Employee Benefit - Expenses',
    'Employee Benefit - Hardik',
    'Employee Benefit - Rose',
    'Employee Benefit - Yogi',
    'Excise Tax Payable',
    'Expense for DishNet 4G',
    'Flowrance Commission - ICAP',
    'Flyfine Digital Energy Co Ltd',
    'Food & Other Exp',
    'Food Allowances Payable To Amos',
    'Food Allowances Payable To Atul',
    'Food Allowances Payable To Bidali',
    'Food Allowances Payable To Dikko',
    'Food Allowances Payable To Emmanuel',
    'Food Allowances Payable To John Ochiti',
    'Food Allowances Payable To Kammanda',
    'Food Allowances Payable To Mackline Anena',
    'Food Allowances Payable To Modi Mawa Francis',
    'Food Allowances Payable To Paji (Shamshare Singh)',
    'Food Allowances Payable To Rupesh',
    'Food Allowances Payable To Stephen',
    'Food Allowances Payable to Bhavin',
    'Food Allowances Payable to Nirav',
    'Food Allowances Payable to Yash',
    'Fred Commission - FLDA',
    'Friends IT Services (Creditor)',
    'Furniture & Fixtures',
    'Gulliver Technologies Solutions',
    'Hussain Commission - Hard Rock',
    'Infinity Group Commission - statement Group',
    'Intersat Communication Services FZCO / BSS Africa',
    'Iseih John (Mr. Migbiakum) Commission',
    'Jackson Commission - Health Link',
    'Jerry Commission - PAH',
    'Jiaxing Feiya New Energy Co. Ltd',
    'John Commission - Health Net TPO',
    'Juma Commission - PAH',
    'Justin Commission - JAM',
    'Kachi Commission - ICAP',
    'Kennedy Bidali Commission - Afenet',
    'Kuol Bol Commission - CEN',
    'LEOKONNECT LIMITED (STAR LINK)',
    'Ladu Augustino Commission - WS Insight',
    'Legal fees',
    'Liquid Telecom',
    'Loan Given Moses Geu (lawyer) (Loan & Advance)',
    'Loan Given To Bhavin',
    'Loan Given To Paji (Shamshare Singh)',
    'Loan Taken from Atul (Unsecured Loan)',
    'Loan from Bhavin',
    'Loan given to Modi Mawa Francis',
    'Loan taken from Chirag Patel',
    'Loan to Ark Angelo (Visa Consultant)',
    'Local Purchase',
    'MR. Penge-CHECL',
    'MSF Rose Commission - MSF',
    'Maama Bakery (Investment)',
    'Mabe Abanji Commission - WRSS',
    'Medical Exps',
    'Micheal Amos Commission - NRC',
    'Micheal Commission - AFENET',
    'Minerva Technologies',
    'Misc. Expenses',
    'Monica Commission - ICAP',
    'Moris Commission - JMC',
    'Moris Commission - South University',
    'Mr. Dada Gideon Commission - NRC',
    'Mr. Fei Commission - Embassy of china',
    'Mr. Francis Commission - WRSS Site',
    'Mr. Jackton Commission - UNDP',
    'Mr. Li Commission - CHINA JIANGSU INTERNATIONAL',
    'Mr. Manage Commission - Embassy of china',
    'Mr. Robert Commission - Catholic Diocese of Rumbek',
    'Mr. Robert Commission - NPA',
    'Mr.Brown Bismark Commission - UNH',
    'Mr.Mutika Justin Ghatanyaki Commission - For Afrika',
    'Mrs. Bena Commission - UNDP Bentiu & Wau',
    'Mrs. Marry Mawa Commission - (ICCO)',
    'Mrs. Marry Mawa Commission - SSUPD',
    'Mrs. Marry Mawa Commission - Universal Church',
    'Murtada commission - RAMS',
    'NCA (National Communication Authority) Fees',
    'NRA Audit (Expenses)',
    'NRA Audit Fees Payable',
    'OYEI Times (Shenzhen) Co. Ltd',
    'Office Expenses',
    'Operational Annual Fees - NCA',
    'PIT Tax Payable',
    'Paji (Shamshare Singh) Capital a/c',
    'Papa Commission - ICAP',
    'Peter Commission - ICAP',
    'Plot No. 141 ( Lokiliri Payam )',
    'Plot No. 286 ( Luri )',
    'Plot No. 291 & 292 ( Luri )',
    'Plot at Kwarjik - Bilpam Road',
    'Printing & Stationery',
    'Purchase',
    'Remuneration payable - Bhavin Madlani',
    'Remuneration payable - Paji (Shamshare Singh)',
    'Remuneration payable - Tom Joseph luate',
    'Renewal Charges',
    'Rent Payable - Tower at GMSH',
    'Rent Payable - UAP Tower',
    'Salary Payable Moses Geu - Lawyer',
    'Salary Payable To Tabule Malish',
    'Salary Payable To Vivek Bhatt',
    'Salary Payable to Geoffrey',
    'Salary payable - Komal Madlani',
    'Salary payable To Amos',
    'Salary payable To Atip Security',
    'Salary payable To Atul',
    'Salary payable To Bhavin',
    'Salary payable To Bidali',
    'Salary payable To Charles',
    'Salary payable To Dikko',
    'Salary payable To Emmanuel',
    'Salary payable To John Ochiti',
    'Salary payable To Joseph Security',
    'Salary payable To Justus',
    'Salary payable To Kammanda',
    'Salary payable To Kennedy',
    'Salary payable To Mackline Anena',
    'Salary payable To Margret 1',
    'Salary payable To Margret 2',
    'Salary payable To Modi Mawa Francis',
    'Salary payable To Mumma Marry',
    'Salary payable To Mumma Rose',
    'Salary payable To Nancy - House Keeper',
    'Salary payable To Nirav',
    'Salary payable To Paji (Shamshare Singh)',
    'Salary payable To Rupesh',
    'Salary payable To Stephen',
    'Salary payable To William Security',
    'Salary payable To Yash',
    'Salary to John Security',
    'Shafik Commission - HRSS',
    'Site Expenses',
    'Sky Trips',
    'Software Charges',
    'Splynx s.r.o.',
    'Starlink - Nirav Eco bank a/c',
    'Stephen Eku Commission - JSI',
    'Tom Capital a/c',
    'Tom Commission - WHO',
    'Transfer Charges',
    'Transport & Freight charges',
    'Travelling & Site Exps (Local)',
    'Travelling Allowance payable - Bidali',
    'Travelling Allowance payable - Charles',
    'Travelling Allowance payable - Christine',
    'Travelling Allowance payable - Dikko',
    'Travelling Allowance payable - Emmanuel',
    'Travelling Allowance payable - John Ochiti',
    'Travelling Allowance payable - Kammanda',
    'Travelling Allowance payable - Kennedy',
    'Travelling Allowance payable - Mackline Anena',
    'Travelling Allowance payable - Margret 1',
    'Travelling Allowance payable - Margret 2',
    'Travelling Allowance payable - Modi Mawa Francis',
    'Travelling Allowance payable - Mumma Marry',
    'Travelling Allowance payable - Mumma Rose',
    'Travelling Allowance payable - Stephen',
    'Travelling Exps (Yearly)',
    'Travelling allowances Payable To Paji (Shamshare Singh)',
    'UPCL',
    'USAF Fees - Expense',
    'VSATplus International Inc',
    'Vehicle Exps',
    'Victoria Commission - AFENET',
    'Vietnam Commission - Vietnam Level-II',
    'Visa & Alliance Exps',
    'WT (Rental Tax) Tax Payable',
    'Waka General Trading Co. (Unsecured Loan)',
    'XCEED NET',
];
