<?php
// Tab: faq
// Extracted from public.php on 2026-03-15
?>
    <div class="kyc-card"><div class="kyc-card-header"><i class="bi bi-question-circle"></i> Frequently Asked Questions</div>
    <div style="padding:12px 20px;color:#6b7280;font-size:13px;">Tap any question to see the answer.</div></div>
    <style>.faq-i{border:1px solid #e5e7eb;border-radius:8px;margin-bottom:8px;background:#fff;}.faq-q{padding:14px 20px;font-weight:600;font-size:13px;cursor:pointer;display:flex;justify-content:space-between;align-items:center;}.faq-q:hover{background:#f9fafb;}.faq-q .ar{transition:transform .2s;color:#9ca3af;}.faq-i.op .faq-q .ar{transform:rotate(180deg);}.faq-a{display:none;padding:0 20px 16px;font-size:13px;line-height:1.8;color:#374151;border-top:1px solid #f3f4f6;}.faq-i.op .faq-a{display:block;padding-top:12px;}.faq-c{font-size:12px;font-weight:800;text-transform:uppercase;letter-spacing:.5px;color:#1565C0;padding:16px 0 8px;}</style>

    <div class="faq-c">&#128181; Collecting Payments</div>
    <div class="faq-i"><div class="faq-q" onclick="this.parentElement.classList.toggle('op')">How do I collect a payment from an existing customer?<span class="ar">&#9660;</span></div><div class="faq-a">Go to <strong>Collect Payment</strong> tab → search customer name → select them → enter amount → tap Collect. The amount is deducted from your wallet and posted to CRM.</div></div>
    <div class="faq-i"><div class="faq-q" onclick="this.parentElement.classList.toggle('op')">What if the customer is not found in search?<span class="ar">&#9660;</span></div><div class="faq-a">The customer may not be in CRM yet. Register them first via <strong>New KYC</strong>. After CRM sync completes, you can collect payments. You can also type the name manually.</div></div>
    <div class="faq-i"><div class="faq-q" onclick="this.parentElement.classList.toggle('op')">Does the payment go to the CRM automatically?<span class="ar">&#9660;</span></div><div class="faq-a">Yes — when you collect a payment, it is posted to UCRM immediately via the API. UCRM then sends the customer an email receipt automatically. Your wallet is debited and the invoice is marked paid in UCRM in one step.</div></div>
    <div class="faq-i"><div class="faq-q" onclick="this.parentElement.classList.toggle('op')">Which amount buttons should I use for monthly plans?<span class="ar">&#9660;</span></div><div class="faq-a"><strong>Starlink:</strong> $65, $80, $112, $218 etc. <strong>Fiber:</strong> $50, $75, $100. <strong>SIM Data:</strong> $25, $40, $80, $110, $120, $200, $250. Check the <strong>Help Guide</strong> for full pricing.</div></div>

    <div class="faq-c">&#128100; My Account</div>
    <div class="faq-i"><div class="faq-q" onclick="this.parentElement.classList.toggle('op')">I logged in but I'm being asked to change my password.<span class="ar">&#9660;</span></div><div class="faq-a">New accounts are created with a default password of <strong>123456</strong>. You must set your own password (minimum 8 characters) before you can use the system. This is a one-time step for security.</div></div>
    <div class="faq-i"><div class="faq-q" onclick="this.parentElement.classList.toggle('op')">Do I get commission on collections or KYC registrations?<span class="ar">&#9660;</span></div><div class="faq-a">DishNet sales staff are on company payroll, so commission is not calculated. Your earnings come through your regular salary. If you are an external partner agent, your admin will configure your commission rate separately.</div></div>
    <div class="faq-i"><div class="faq-q" onclick="this.parentElement.classList.toggle('op')">How do I change my password?<span class="ar">&#9660;</span></div><div class="faq-a">Go to <strong>More → Profile</strong> tab → find the Change Password section → enter your new password (min 8 characters) → save. If you forgot your current password, ask your admin to reset it.</div></div>

    <div class="faq-c">&#128176; Wallet &amp; Balance</div>
    <div class="faq-i"><div class="faq-q" onclick="this.parentElement.classList.toggle('op')">Why is my balance low?<span class="ar">&#9660;</span></div><div class="faq-a">Each payment collection and KYC submission deducts from your wallet. Go to <strong>Recharge Wallet</strong> → upload bank/mobile money proof → admin approves within 1-2 hours.</div></div>
    <div class="faq-i"><div class="faq-q" onclick="this.parentElement.classList.toggle('op')">I was charged but KYC failed. Will I get a refund?<span class="ar">&#9660;</span></div><div class="faq-a">Yes, automatically! If CRM sync fails 3 times, the system reverses the debit. Check your <strong>My Wallet</strong> passbook for a "reversal" entry.</div></div>
    <div class="faq-i"><div class="faq-q" onclick="this.parentElement.classList.toggle('op')">Can I be double-charged?<span class="ar">&#9660;</span></div><div class="faq-a">No. The system uses idempotency keys to prevent double charges even if you accidentally tap submit twice.</div></div>
    <div class="faq-i"><div class="faq-q" onclick="this.parentElement.classList.toggle('op')">How do I check my transaction history?<span class="ar">&#9660;</span></div><div class="faq-a">Go to <strong>My Wallet</strong> tab. You'll see your balance, total in/out, and full passbook with every transaction.</div></div>

    <div class="faq-c">&#128203; New Customer Registration</div>
    <div class="faq-i"><div class="faq-q" onclick="this.parentElement.classList.toggle('op')">What documents does the customer need?<span class="ar">&#9660;</span></div><div class="faq-a">A <strong>passport photo</strong> (can use phone camera) and a <strong>national ID or passport</strong> scan/photo. JPEG or PNG, under 5MB each.</div></div>
    <div class="faq-i"><div class="faq-q" onclick="this.parentElement.classList.toggle('op')">What's the difference between Starlink, Fiber, and SIM?<span class="ar">&#9660;</span></div><div class="faq-a"><strong>Starlink:</strong> Satellite dish kit + monthly plan. <strong>Fiber:</strong> FTTH connection with WiFi ONU/router. <strong>SIM Card:</strong> Data network with monthly/package plans (Silver, Gold, Platinum, Diamond).</div></div>
    <div class="faq-i"><div class="faq-q" onclick="this.parentElement.classList.toggle('op')">Application stuck on "pending_sync"?<span class="ar">&#9660;</span></div><div class="faq-a">System syncs every minute via cron. If stuck more than 30 minutes, contact admin to check the Sync Queue.</div></div>
    <div class="faq-i"><div class="faq-q" onclick="this.parentElement.classList.toggle('op')">Can I edit a submitted application?<span class="ar">&#9660;</span></div><div class="faq-a">Only the CRM username can be changed by admin. For other errors, submit a new KYC application.</div></div>

    <?php /* SIM Cards FAQ */ ?>
    <div class="faq-i"><div class="faq-q" onclick="this.parentElement.classList.toggle('op')">How do I register a SIM card for a customer?<span class="ar">&#9660;</span></div><div class="faq-a">In New KYC → select <strong>SIM Card</strong> → enter customer info → fill SIM details (ICCID, MSISDN) → select a data plan (Silver $40 – Diamond $250) → submit.</div></div>
    <div class="faq-i"><div class="faq-q" onclick="this.parentElement.classList.toggle('op')">What SIM plans are available?<span class="ar">&#9660;</span></div><div class="faq-a"><strong>Silver</strong> $40 (30d) | <strong>Gold</strong> $80 (30d) | <strong>Platinum</strong> $110 (30d) | <strong>Diamond</strong> $250 (30d) | <strong>Silver90</strong> $120 (90d) | <strong>Silver180</strong> $200 (180d) | <strong>Silver25</strong> $25 (15d, 2Mbps). All unlimited data.</div></div>

    <div class="faq-c">&#128178; Pricing &amp; Amounts</div>
    <div class="faq-i"><div class="faq-q" onclick="this.parentElement.classList.toggle('op')">How is the wallet deduction calculated for a Cash KYC registration?<span class="ar">&#9660;</span></div><div class="faq-a">For <strong>Starlink</strong>: plan monthly price + hardware/kit price. For <strong>Fiber (FTTH)</strong>: plan monthly price + installation fee (configurable in Settings, default $100). For <strong>SIM</strong>: plan price only. The deduction equals the total amount the customer paid you.</div></div>
    <div class="faq-i"><div class="faq-q" onclick="this.parentElement.classList.toggle('op')">I registered a cash customer — does the payment appear in CRM immediately?<span class="ar">&#9660;</span></div><div class="faq-a">Yes. When sales type is <strong>Cash</strong>, the plugin posts the payment immediately to UCRM as a credit balance on the customer account. The invoice is created later (after installation). UCRM automatically applies the credit when the invoice is generated — so the customer starts with zero balance.</div></div>
    <div class="faq-i"><div class="faq-q" onclick="this.parentElement.classList.toggle('op')">What is a Credit registration vs Cash registration?<span class="ar">&#9660;</span></div><div class="faq-a"><strong>Cash</strong> — Customer paid the agent immediately. Wallet is debited, payment posted to CRM, customer created as Regular Client. <strong>Credit</strong> — Customer will pay later. No wallet deduction, no payment posted. Customer is created as a Lead in CRM until admin confirms payment received.</div></div>
    <div class="faq-i"><div class="faq-q" onclick="this.parentElement.classList.toggle('op')">Where does the commission come from?<span class="ar">&#9660;</span></div><div class="faq-a">Commission is auto-calculated as a percentage of each collection (configurable per service type in Settings). For DishNet payroll staff commission is set to 0%. For external partner agents, the admin sets the rate. Commission is credited to the wallet automatically after each approved collection.</div></div>

    <div class="faq-c">&#128241; WhatsApp Notifications</div>
    <div class="faq-i"><div class="faq-q" onclick="this.parentElement.classList.toggle('op')">Why are WhatsApp notifications not sending?<span class="ar">&#9660;</span></div><div class="faq-a">Go to the <strong>💬 WhatsApp tab</strong> in the left sidebar (admin only). Enter: <strong>WASender Server URL</strong> (http://wa.dishnetafrica.com), <strong>App Key</strong>, and <strong>Auth Key</strong> — these are from the WASender server. Enter the phone numbers for Support and Accounts. Click <strong>Save WhatsApp Settings</strong>.</div></div>
    <div class="faq-i"><div class="faq-q" onclick="this.parentElement.classList.toggle('op')">Which WhatsApp events are handled by WASender automatically (not by this plugin)?<span class="ar">&#9660;</span></div><div class="faq-a">UCRM billing events are handled <strong>directly by WASender's built-in UCRM listener</strong> — our plugin never touches these: Invoice created, Payment received, Service suspended/restored, Client welcome. Our plugin only sends operational events that UCRM does not know about: KYC submitted, Wallet top-up, Recharge approved/rejected, Cash handover, Lead assigned, LTE alerts, Overdue reminders.</div></div>
    <div class="faq-i"><div class="faq-q" onclick="this.parentElement.classList.toggle('op')">How do I send a manual WhatsApp notification?<span class="ar">&#9660;</span></div><div class="faq-a">Go to the <strong>Notify tab</strong> (admin only). Select event type, enter phone number and message → Send. You can also trigger installation confirmations, outage alerts, and commission summaries from there.</div></div>

    <div class="faq-c">&#128273; Usernames &amp; CRM IDs</div>
    <div class="faq-i"><div class="faq-q" onclick="this.parentElement.classList.toggle('op')">How are FTTH and Starlink usernames generated?<span class="ar">&#9660;</span></div><div class="faq-a">Usernames are auto-generated with a prefix + 6-digit number: <strong>Starlink → STAR000053</strong>, <strong>Fiber → FTTH000241</strong>. The number auto-increments from the last used number in the database. The admin can configure the starting number in <strong>Settings → Username Sequence</strong> to continue from the old system (e.g. set 52 for Starlink to get STAR000053 next).</div></div>
    <div class="faq-i"><div class="faq-q" onclick="this.parentElement.classList.toggle('op')">Can an agent choose a custom CRM username?<span class="ar">&#9660;</span></div><div class="faq-a">Yes — on the KYC form there is an optional <strong>CRM Username</strong> field. If left blank, the system auto-generates FTTH/STAR username. If filled, the custom username is validated for uniqueness and format (letters, numbers, hyphens, underscores, 3–50 chars).</div></div>
    <div class="faq-i"><div class="faq-q" onclick="this.parentElement.classList.toggle('op')">Can a username be changed after submission?<span class="ar">&#9660;</span></div><div class="faq-a">Admin can change the CRM username before the customer is provisioned (service activated). Go to <strong>All Applications</strong> → find the application → Edit Username. After provisioning, username changes must be done directly in UCRM.</div></div>

    <div class="faq-c">&#128202; Admin &amp; Accounts</div>
    <div class="faq-i"><div class="faq-q" onclick="this.parentElement.classList.toggle('op')">What does "Net Due to DishNet" mean in the ledger?<span class="ar">&#9660;</span></div><div class="faq-a">It is the total amount the agent has collected from customers <strong>minus their earned commission</strong>. This is the amount the agent must remit to the company. Formula: <code>Net Due = Total Collected − Commission Earned</code>.</div></div>
    <div class="faq-i"><div class="faq-q" onclick="this.parentElement.classList.toggle('op')">How does wallet recharge work for an agent?<span class="ar">&#9660;</span></div><div class="faq-a">Agent submits recharge request with payment proof (bank transfer / mobile money). Admin reviews and approves in <strong>Accounts → Recharge History</strong>. On approval, wallet is credited automatically. Rejected requests show the reason.</div></div>
    <div class="faq-i"><div class="faq-q" onclick="this.parentElement.classList.toggle('op')">Why does an agent see "UCRM User ID Not Linked" on My Jobs?<span class="ar">&#9660;</span></div><div class="faq-a">The agent's retailer profile needs a UCRM User ID to fetch their jobs. Admin: go to <strong>Retailers → Edit Retailer</strong> → find the <strong>UCRM User ID</strong> field → enter the number from UCRM's URL when viewing that user (e.g. /system/users/<strong>23</strong>/edit → enter 23).</div></div>
    <div class="faq-i"><div class="faq-q" onclick="this.parentElement.classList.toggle('op')">How do I approve or reject a wallet recharge request?<span class="ar">&#9660;</span></div><div class="faq-a">Go to <strong>Accounts → Recharge History</strong>. Pending requests show an Approve / Reject button. Approving immediately credits the agent's wallet and sends a WhatsApp confirmation. Rejecting requires a reason which is shown to the agent.</div></div>

