<?php
declare(strict_types=1);
chdir(dirname(__DIR__));

/**
 * dpo_payment_method.php — settle, on this install, which uCRM payment method
 * a DPO Pay payment is booked against, and put its UUID in the vault.
 *
 * ── WHY THIS TOOL EXISTS ────────────────────────────────────────────────
 *
 * lib/PaymentUuids.php records that this uCRM instance has no mobile-money
 * method at all, and that every unknown slug falls back to Cash. Cash in uCRM
 * feeds agent cash reconciliation — so a DPO payment booked as Cash becomes
 * money an agent is expected to hand over and never held. A dedicated method
 * is therefore a prerequisite for the integration, not a tidy-up afterwards.
 *
 * The UUID is generated by uCRM, so it cannot be written in advance. This tool
 * finds or creates the method against the LIVE instance and reports what it
 * actually found, rather than assuming an API capability.
 *
 * ── WHAT IT DOES ────────────────────────────────────────────────────────
 *
 *   --list     show every payment method this uCRM holds, with its UUID
 *   (default)  find a DPO method; if absent, TRY to create one and say
 *              exactly what uCRM answered
 *   --store    additionally write the UUID into the ConfigVault
 *
 * If uCRM refuses to create payment methods over the API — which is possible,
 * and is not something this tool pretends to know in advance — it prints the
 * refusal verbatim and the manual path. Re-run with --store afterwards.
 *
 * Run inside the ucrm container, from the plugin directory:
 *   php tools/dpo_payment_method.php --list
 *   php tools/dpo_payment_method.php
 *   php tools/dpo_payment_method.php --store
 */

if (PHP_SAPI !== 'cli') { http_response_code(403); exit("CLI only\n"); }

$root = dirname(__DIR__);
require_once $root . '/lib/error_handler.php';
require_once $root . '/lib/bootstrap_data.php';
require_once $root . '/lib/StoreInterface.php';
require_once $root . '/lib/SqliteStore.php';
require_once $root . '/lib/PluginConfig.php';
require_once $root . '/lib/ConfigVault.php';
require_once $root . '/lib/CrmApiClient.php';

$argvAll = $argv ?? [];
$doList  = in_array('--list',  $argvAll, true);
$doStore = in_array('--store', $argvAll, true);

$dataDir = getDataDir($root);
$config  = PluginConfig::load($root, $dataDir);
$crm     = CrmApiClient::fromUcrm($root, $config);
if (!$crm->isConfigured()) exit("uCRM API not configured — nothing to ask.\n");

const DPO_METHOD_NAME = 'DPO Pay';

echo "\nDPO Pay — uCRM payment method\n";
echo "─────────────────────────────────────────────────────────────\n";
echo "uCRM: " . $crm->getBaseUrl() . "\n\n";

$methods = $crm->get('payment-methods');
if (!is_array($methods)) {
    $e = $crm->getLastError();
    exit("Could not read payment-methods: " . json_encode($e ?: []) . "\n");
}

$rows = [];
foreach ($methods as $m) {
    if (!is_array($m) || empty($m['id'])) continue;
    $rows[] = ['id'   => (string)$m['id'],
               'name' => (string)($m['name'] ?? ''),
               // uCRM does not expose an 'active' flag consistently across
               // versions; print whatever it gave rather than inventing one.
               'raw'  => $m];
}

echo count($rows) . " payment method(s) on this instance:\n\n";
foreach ($rows as $r) {
    printf("  %-38s  %s\n", $r['id'], $r['name'] !== '' ? $r['name'] : '(unnamed)');
}
echo "\n";

if ($doList) {
    echo "Listing only. Re-run without --list to find or create the DPO method.\n";
    return;
}

// ── Already there? ──────────────────────────────────────────────────────
$found = null;
foreach ($rows as $r) {
    if (stripos($r['name'], 'dpo') !== false) { $found = $r; break; }
}

if ($found === null) {
    echo "No DPO method found. Asking uCRM to create one…\n\n";
    $created = $crm->post('payment-methods', ['name' => DPO_METHOD_NAME]);
    if (is_array($created) && !empty($created['id'])) {
        $found = ['id' => (string)$created['id'], 'name' => (string)($created['name'] ?? DPO_METHOD_NAME)];
        echo "  created: {$found['id']}  {$found['name']}\n\n";
    } else {
        $e = $crm->getLastError();
        echo "  uCRM did NOT create it. It answered:\n";
        echo "  " . json_encode($e ?: $created, JSON_UNESCAPED_SLASHES) . "\n\n";
        echo "  This is not necessarily a fault: uCRM may expose payment methods\n";
        echo "  read-only over the API. Create it by hand instead —\n\n";
        echo "      uCRM → System → Billing → Payment methods → Add\n";
        echo "      Name: " . DPO_METHOD_NAME . "\n\n";
        echo "  then re-run:  php tools/dpo_payment_method.php --store\n\n";
        return;
    }
}

echo "DPO payment method\n";
echo "  UUID: {$found['id']}\n";
echo "  Name: {$found['name']}\n\n";

if (!$doStore) {
    echo "Not stored. To put it in the vault:\n";
    echo "    php tools/dpo_payment_method.php --store\n\n";
    return;
}

$r = ConfigVault::store($root, $dataDir, ['dpo_payment_method_uuid' => $found['id']]);
if (!empty($r['ok'])) {
    echo "Stored in the vault as dpo_payment_method_uuid.\n";
    echo "It survives a re-install, like the EFRIS keys.\n\n";
} else {
    echo "NOT stored: " . ($r['error'] ?? 'unknown error') . "\n\n";
}
