<?php
declare(strict_types=1);

/**
 * CrmApiClient — DishNet Africa UCRM/UISP API wrapper.
 *
 * ── AUTO-DETECTION (matches Starlink Finance plugin pattern exactly) ──────────
 *
 * UCRM/UISP automatically writes ucrm.json when a plugin is installed.
 * Checked in two locations (same as Starlink Finance v7.0.5):
 *   1. {plugin_root}/ucrm.json
 *   2. {plugin_root}/data/ucrm.json
 *
 * Contents:
 *   { "ucrmPublicUrl":"https://crm.dishnetafrica.com/",
 *     "ucrmLocalUrl":"http://localhost/",
 *     "pluginAppKey":"<auto-generated key>",
 *     "pluginId":123 }
 *
 * API header:  X-Auth-App-Key: {pluginAppKey}
 * API base:    {ucrmLocalUrl}/api/v2.1/
 *
 * Zero manual configuration needed — upload ZIP, plugin works.
 *
 * ── MANUAL OVERRIDE ───────────────────────────────────────────────────────────
 * If crm_base_url + crm_auth_token are both set in Settings, they override
 * ucrm.json. Useful for pointing at a different org or staging environment.
 */
class CrmApiClient
{
    private string $baseUrl;
    private string $appKey;
    private string $authHeader; // 'X-Auth-App-Key' (auto) or 'x-auth-token' (manual)
    private array  $lastError = [];

    public function __construct(string $baseUrl, string $appKey, string $authHeader = 'X-Auth-App-Key')
    {
        $this->baseUrl    = rtrim($baseUrl ?: '', '/');
        $this->appKey     = $appKey ?: '';
        $this->authHeader = $authHeader ?: 'X-Auth-App-Key';
    }

    /**
     * Factory — auto-detect from ucrm.json, with manual override.
     * Mirrors Starlink Finance public.php lines 36-46 exactly.
     *
     * @param string $pluginRoot  __DIR__ of the plugin (directory containing public.php)
     * @param array  $config      kyc_config.json contents (crm_base_url, crm_auth_token)
     */
    public static function fromUcrm(string $pluginRoot, array $config = []): self
    {
        // ── Priority 1: Manual override (both fields required) ────────────
        $manualUrl   = trim($config['crm_base_url']   ?? '');
        $manualToken = trim($config['crm_auth_token'] ?? '');
        if ($manualUrl !== '' && $manualToken !== '') {
            return new self($manualUrl, $manualToken, 'x-auth-token');
        }

        // ── Priority 2: Auto from ucrm.json (Starlink Finance pattern) ───
        $ucrmConfig = [];
        foreach ([$pluginRoot . '/ucrm.json', $pluginRoot . '/data/ucrm.json'] as $path) {
            if (file_exists($path)) {
                $c = json_decode(file_get_contents($path), true);
                if (is_array($c) && !empty($c)) { $ucrmConfig = $c; break; }
            }
        }

        // Prefer local URL (same-server, fastest); fall back to public URL
        $apiUrl = $ucrmConfig['ucrmLocalUrl'] ?? ($ucrmConfig['ucrmPublicUrl'] ?? '');
        $appKey = $ucrmConfig['pluginAppKey'] ?? '';

        if ($apiUrl !== '' && $appKey !== '') {
            // v4.21.81: upgraded to UISP API v2.1 — v1.0 dropped PDF + some endpoints
            $apiBase = rtrim($apiUrl, '/') . '/api/v2.1';
            return new self($apiBase, $appKey, 'X-Auth-App-Key');
        }

        // Not configured
        return new self('', '');
    }

    // ── CRUD helpers ──────────────────────────────────────────────────────────

    public function get(string $path): ?array             { return $this->request('GET',   $path); }
    public function getBaseUrl(): string { return $this->baseUrl; }
    public function getAppKey(): string { return $this->appKey; }
    public function getAuthHeader(): string { return $this->authHeader; }

    /**
     * POST to CRM API.
     *
     * When posting to 'payments', automatically checks whether the client
     * is still a Lead (clientType=1) and upgrades them to Client (clientType=2)
     * first. This prevents HTTP 422 "This action is not possible, while the
     * client is lead." across ALL payment post sites — one fix, everywhere.
     */
    public function post(string $path, array $p = []): ?array
    {
        if ($path === 'payments' && !empty($p['clientId'])) {
            $clientId = (int)$p['clientId'];
            try {
                $client = $this->request('GET', "clients/{$clientId}");
                if ($client && (int)($client['clientType'] ?? 2) === 1) {
                    // Client is a Lead — convert to Client before payment
                    $this->request('PATCH', "clients/{$clientId}", ['clientType' => 2]);
                }
            } catch (\Throwable $e) { /* non-fatal — proceed anyway */ }
        }
        return $this->request('POST', $path, $p);
    }

    public function patch(string $path, array $p = []): ?array  { return $this->request('PATCH',  $path, $p); }
    public function delete(string $path): ?array                { return $this->request('DELETE', $path); }

    /**
     * Download raw binary content (e.g. invoice PDF).
     * Returns base64-encoded content, or null on failure.
     */
    public function getRawContent(string $path): ?string
    {
        $url = $this->baseUrl . '/' . ltrim($path, '/');
        $ch  = curl_init($url);
        curl_setopt_array($ch, [
            CURLOPT_RETURNTRANSFER => true,
            CURLOPT_HTTPHEADER     => [$this->authHeader . ': ' . $this->appKey],
            CURLOPT_TIMEOUT        => 30,
            CURLOPT_FOLLOWLOCATION => true,
            CURLOPT_SSL_VERIFYPEER => false,
        ]);
        $response = curl_exec($ch);
        $httpCode = (int)curl_getinfo($ch, CURLINFO_HTTP_CODE);
        curl_close($ch);
        if ($httpCode !== 200 || $response === false || strlen($response) < 100) return null;
        return base64_encode($response);
    }

    // ── SAFE PAYMENT CREATION (Duplicate Prevention) ─────────────────────────
    
    /**
     * Create payment in UCRM only if it doesn't already exist.
     * 
     * UCRM is the source of truth. Before creating, we check:
     * 1. Existing payments for this client
     * 2. Match by unique reference in note (e.g., "Ref: KYC-1234" or "Ref: PAY-5678")
     * 3. Match by amount + date (same day, exact amount)
     * 
     * @param array  $payload   Standard UCRM payment payload
     * @param string $uniqueRef Unique reference to search for (e.g., "KYC-1234", "PAY-5678")
     * @return array ['success' => bool, 'id' => int|null, 'duplicate' => bool, 'error' => string]
     */
    public function createPaymentSafe(array $payload, string $uniqueRef = ''): array
    {
        $clientId = (int)($payload['clientId'] ?? 0);
        $amount   = (float)($payload['amount'] ?? 0);
        
        if ($clientId <= 0) {
            return ['success' => false, 'id' => null, 'duplicate' => false, 'error' => 'Invalid clientId'];
        }
        if ($amount <= 0) {
            return ['success' => false, 'id' => null, 'duplicate' => false, 'error' => 'Invalid amount'];
        }
        
        // ── Check for existing payment in UCRM ──
        // Fetch recent payments for this client (last 30 days)
        $since = date('Y-m-d', strtotime('-30 days'));
        $existingPayments = $this->get("payments?clientId={$clientId}&createdDateFrom={$since}");
        
        if (is_array($existingPayments) && !empty($existingPayments)) {
            foreach ($existingPayments as $existing) {
                $existingAmount = (float)($existing['amount'] ?? 0);
                $existingNote   = (string)($existing['note'] ?? '');
                $existingDate   = substr($existing['createdDate'] ?? '', 0, 10); // YYYY-MM-DD
                $todayDate      = date('Y-m-d');
                
                // Method 1: Match by unique reference in note
                if ($uniqueRef !== '' && stripos($existingNote, $uniqueRef) !== false) {
                    error_log("[CrmApiClient] DUPLICATE PREVENTED: Payment with ref '{$uniqueRef}' already exists (ID: {$existing['id']})");
                    return [
                        'success'   => true,
                        'id'        => (int)$existing['id'],
                        'duplicate' => true,
                        'message'   => "Payment already exists with ref: {$uniqueRef}",
                    ];
                }
                
                // Method 2: Match by exact amount + same day (fallback)
                //
                // v4.21.57 — invoice-aware dedup. Previously this method
                // treated ANY same-amount same-day same-client payment as a
                // duplicate, even when the new payment targeted a different
                // invoice. That silently dropped legitimate second payments
                // when staff collected for two invoices same-day at the
                // same per-invoice amount (e.g. $50 for inv 000024 then
                // $50 for inv 000025). We now require that the invoice
                // targeting also matches before declaring a duplicate.
                if (abs($existingAmount - $amount) < 0.01 && $existingDate === $todayDate) {
                    // Compare invoice targets — if BOTH payments target the
                    // same specific invoice (or both are auto-apply), only
                    // then consider this a duplicate. Different invoices =
                    // legitimate separate payments.
                    $newInvoiceIds      = $payload['invoiceIds'] ?? [];
                    $existingInvoiceIds = [];
                    if (is_array($existing['invoices'] ?? null)) {
                        foreach ($existing['invoices'] as $exInv) {
                            if (is_array($exInv) && isset($exInv['id'])) {
                                $existingInvoiceIds[] = (int)$exInv['id'];
                            } elseif (is_numeric($exInv)) {
                                $existingInvoiceIds[] = (int)$exInv;
                            }
                        }
                    }
                    sort($newInvoiceIds);
                    sort($existingInvoiceIds);
                    $invoiceTargetsDiffer = ($newInvoiceIds !== $existingInvoiceIds);
                    if ($invoiceTargetsDiffer) {
                        // Different invoices → not a duplicate, keep checking
                        continue;
                    }

                    // v4.21.103: Both payments have empty invoiceIds = both
                    // are auto-apply. UCRM applies each to the oldest open
                    // invoice, so two auto-applies actually go to TWO
                    // different invoices (e.g. $100 to inv 0024, then $100
                    // to inv 0025). Treating them as duplicate suppresses
                    // legitimate second payment and leaves customer short
                    // in CRM. Real-world case: Mohamed Rashid #000037 paid
                    // 2 x \$100 same day for 2 months subscription — only
                    // first reached UCRM, second silently dropped.
                    // Fix: if both lists are empty, this is NOT a duplicate.
                    if (empty($newInvoiceIds) && empty($existingInvoiceIds)) {
                        error_log("[CrmApiClient] Two auto-apply payments same day — treating as separate (v4.21.103). client={$clientId} amount={$amount}");
                        continue;
                    }

                    // Check if note contains any of our known prefixes
                    $ourPrefixes = ['KYC-', 'PAY-', 'DishNet', 'Sales Hub', 'Wallet'];
                    $isOurPayment = false;
                    foreach ($ourPrefixes as $prefix) {
                        if (stripos($existingNote, $prefix) !== false) {
                            $isOurPayment = true;
                            break;
                        }
                    }
                    
                    // Also check if new note matches existing note closely
                    $newNote = $payload['note'] ?? '';
                    if ($isOurPayment || ($newNote !== '' && stripos($existingNote, substr($newNote, 0, 30)) !== false)) {
                        error_log("[CrmApiClient] DUPLICATE PREVENTED: Payment \${$amount} for client {$clientId} already exists today (ID: {$existing['id']})");
                        return [
                            'success'   => true,
                            'id'        => (int)$existing['id'],
                            'duplicate' => true,
                            'message'   => "Payment \${$amount} already exists for today",
                        ];
                    }
                }
            }
        }
        
        // ── No duplicate found - create new payment ──
        $result = $this->post('payments', $payload);
        
        if (!empty($result['id'])) {
            return [
                'success'   => true,
                'id'        => (int)$result['id'],
                'duplicate' => false,
                'message'   => 'Payment created',
            ];
        }
        
        return [
            'success'   => false,
            'id'        => null,
            'duplicate' => false,
            'error'     => $this->getLastError()['message'] ?? 'Payment creation failed',
        ];
    }
    
    /**
     * Check if a payment already exists in UCRM for given client/amount/reference.
     * 
     * @param int    $clientId
     * @param float  $amount
     * @param string $uniqueRef  Reference string to search in notes
     * @return array|null  Existing payment data if found, null otherwise
     */
    public function findExistingPayment(int $clientId, float $amount, string $uniqueRef = ''): ?array
    {
        if ($clientId <= 0) return null;
        
        $since = date('Y-m-d', strtotime('-30 days'));
        $payments = $this->get("payments?clientId={$clientId}&createdDateFrom={$since}");
        
        if (!is_array($payments)) return null;
        
        foreach ($payments as $p) {
            $pAmount = (float)($p['amount'] ?? 0);
            $pNote   = (string)($p['note'] ?? '');
            
            // Match by reference
            if ($uniqueRef !== '' && stripos($pNote, $uniqueRef) !== false) {
                return $p;
            }
            
            // Match by exact amount on same day
            $pDate = substr($p['createdDate'] ?? '', 0, 10);
            if (abs($pAmount - $amount) < 0.01 && $pDate === date('Y-m-d')) {
                return $p;
            }
        }
        
        return null;
    }

    public function getLastError(): array { return $this->lastError; }
    public function isConfigured(): bool  { return $this->baseUrl !== '' && $this->appKey !== ''; }

    /**
     * Credential source for Settings UI: 'auto' | 'manual' | 'none'
     */
    public function getSource(string $pluginRoot, array $config): string
    {
        if (trim($config['crm_base_url'] ?? '') !== '' && trim($config['crm_auth_token'] ?? '') !== '') {
            return 'manual';
        }
        foreach ([$pluginRoot . '/ucrm.json', $pluginRoot . '/data/ucrm.json'] as $path) {
            if (file_exists($path)) {
                $c = json_decode(file_get_contents($path), true) ?? [];
                if (!empty($c['pluginAppKey'])) return 'auto';
            }
        }
        return 'none';
    }

    /**
     * Connectivity test. GET /version exists on all UCRM/UISP installs.
     */
    public function testConnection(string $pluginRoot = '', array $config = []): array
    {
        if (!$this->isConfigured()) {
            return ['ok' => false, 'http_code' => 0, 'source' => 'none',
                    'error' => 'Not configured — ucrm.json not found and no manual credentials set.'];
        }
        $ch = curl_init();
        curl_setopt_array($ch, [
            CURLOPT_URL            => $this->baseUrl . '/version',
            CURLOPT_RETURNTRANSFER => true, CURLOPT_TIMEOUT => 10,
            CURLOPT_SSL_VERIFYPEER => self::curlSslVerify(),
            CURLOPT_HTTPHEADER     => [$this->authHeader . ': ' . $this->appKey, 'Accept: application/json'],
        ]);
        $raw  = curl_exec($ch);
        $code = curl_getinfo($ch, CURLINFO_HTTP_CODE);
        $err  = curl_error($ch);
        curl_close($ch);

        $src = $pluginRoot ? $this->getSource($pluginRoot, $config) : 'unknown';
        if ($err)        return ['ok' => false, 'http_code' => 0,     'error' => "cURL: {$err}",          'source' => $src];
        if ($code === 401) return ['ok' => false, 'http_code' => 401,   'error' => 'Invalid credentials (401)', 'source' => $src];
        if ($code === 403) return ['ok' => false, 'http_code' => 403,   'error' => 'Permission denied (403)',   'source' => $src];
        if ($code >= 400)  return ['ok' => false, 'http_code' => $code, 'error' => "HTTP {$code}",             'source' => $src];
        return ['ok' => true, 'http_code' => $code, 'error' => '', 'source' => $src];
    }

    /**
     * Upload a client document to UCRM as multipart/form-data.
     *
     * UCRM API endpoint:  POST /api/v1.0/clients/{clientId}/documents
     * Fields:             file=<CURLFile>, name=<display name>
     *
     * IMPORTANT: clientId must be in the URL path, NOT a form field.
     * The document appears under the client's Files tab in UCRM.
     *
     * @param string $clientId  UCRM client ID (goes in URL path)
     * @param string $filePath  Server-side absolute path to file
     * @param array  $fields    ['name' => 'Customer Photo.jpg']
     */
    public function upload(string $filePath, array $fields = [], string $clientId = ''): ?array
    {
        if (!file_exists($filePath)) {
            $this->lastError = ['error' => "File not found: {$filePath}"];
            error_log("CrmApiClient::upload: file not found [{$filePath}]");
            return null;
        }

        // UCRM endpoint: /clients/{id}/documents if clientId provided,
        // else fall back to /documents (for template-based docs without a file).
        // For photo/ID uploads clientId is always provided.
        if ($clientId !== '') {
            $endpoint = '/clients/' . rawurlencode($clientId) . '/documents';
        } else {
            // Legacy fallback — template-based doc creation (no file attachment)
            $endpoint = '/documents';
        }

        $mime     = mime_content_type($filePath) ?: 'application/octet-stream';
        // Use the human-readable name from $fields, NOT the PHP temp basename
        $fileName = $fields['name'] ?? basename($filePath);

        $ch = curl_init();
        $uploadOpts = [
            CURLOPT_URL            => $this->baseUrl . $endpoint,
            CURLOPT_RETURNTRANSFER => true,
            CURLOPT_TIMEOUT        => 60,
            CURLOPT_POST           => true,
            CURLOPT_POSTFIELDS     => [
                'name' => $fileName,
                'file' => new \CURLFile($filePath, $mime, $fileName),
            ],
            CURLOPT_SSL_VERIFYPEER => self::curlSslVerify(),
            CURLOPT_SSL_VERIFYHOST => self::curlSslVerify() ? 2 : 0,
            CURLOPT_HTTPHEADER     => [$this->authHeader . ': ' . $this->appKey],
        ];
        $ca = self::caPath();
        if ($ca !== null) $uploadOpts[CURLOPT_CAINFO] = $ca;
        curl_setopt_array($ch, $uploadOpts);
        $raw  = curl_exec($ch);
        $code = curl_getinfo($ch, CURLINFO_HTTP_CODE);
        $err  = curl_error($ch);
        curl_close($ch);

        if ($err) {
            $this->lastError = ['curl_error' => $err];
            error_log("CrmApiClient::upload: cURL error [{$err}] for [{$fileName}] on client [{$clientId}]");
            return null;
        }
        $d = json_decode($raw, true);
        if ($code >= 400) {
            $this->lastError = ['http_code' => $code, 'response' => $d ?? $raw];
            error_log("CrmApiClient::upload: HTTP {$code} for [{$fileName}] on client [{$clientId}] — " . substr($raw, 0, 200));
            return null;
        }
        return is_array($d) ? $d : ['raw' => $raw];
    }

    // ──────────────────────────────────────────────────────────────────────────

    private function request(string $method, string $path, array $payload = []): ?array
    {
        $ch = curl_init();
        $opts = [
            CURLOPT_URL            => $this->baseUrl . '/' . ltrim($path, '/'),
            CURLOPT_RETURNTRANSFER => true,
            CURLOPT_ENCODING       => '',
            CURLOPT_MAXREDIRS      => 5,
            CURLOPT_TIMEOUT        => 30,
            CURLOPT_FOLLOWLOCATION => true,
            CURLOPT_HTTP_VERSION   => CURL_HTTP_VERSION_1_1,
            CURLOPT_CUSTOMREQUEST  => $method,
            CURLOPT_SSL_VERIFYPEER => self::curlSslVerify(),
            CURLOPT_SSL_VERIFYHOST => self::curlSslVerify() ? 2 : 0,
            CURLOPT_HTTPHEADER     => [
                $this->authHeader . ': ' . $this->appKey,
                'Content-Type: application/json',
                'Accept: application/json',
            ],
        ];
        $ca = self::caPath();
        if ($ca !== null) $opts[CURLOPT_CAINFO] = $ca;
        curl_setopt_array($ch, $opts);
        if ($payload) curl_setopt($ch, CURLOPT_POSTFIELDS, json_encode($payload));

        $raw  = curl_exec($ch);
        $code = curl_getinfo($ch, CURLINFO_HTTP_CODE);
        $err  = curl_error($ch);
        curl_close($ch);

        if ($err) { $this->lastError = ['curl_error' => $err]; return null; }
        $d = json_decode($raw, true);
        if ($code >= 400) { $this->lastError = ['http_code' => $code, 'response' => $d ?? $raw]; return null; }
        return is_array($d) ? $d : ['raw' => $raw];
    }

    // ═══════════════════════════════════════════════════════════════════════════
    // WEBHOOK MANAGEMENT
    // ═══════════════════════════════════════════════════════════════════════════

    /**
     * List all webhook endpoints configured in UCRM
     */
    public function getWebhooks(): array
    {
        return $this->get('webhooks/endpoints') ?? [];
    }

    /**
     * Create a new webhook endpoint
     *
     * @param string $url       Full URL to receive webhooks
     * @param array  $events    Event types e.g. ['invoice.add', 'payment.add']
     * @param bool   $verifySsl Whether to verify SSL cert (default true)
     */
    public function createWebhook(string $url, array $events = [], bool $verifySsl = true): ?array
    {
        $payload = [
            'url'                  => $url,
            'isActive'             => true,
            'verifySslCertificate' => $verifySsl,
        ];
        
        // Empty events array = all events
        if (!empty($events)) {
            $payload['eventTypes'] = $events;
        }
        
        return $this->post('webhooks/endpoints', $payload);
    }

    /**
     * Update an existing webhook endpoint
     */
    public function updateWebhook(int $id, array $data): ?array
    {
        return $this->patch("webhooks/endpoints/{$id}", $data);
    }

    /**
     * Delete a webhook endpoint
     */
    public function deleteWebhook(int $id): bool
    {
        $result = $this->delete("webhooks/endpoints/{$id}");
        return $result !== null;
    }

    /**
     * Find webhook by URL pattern
     */
    public function findWebhookByUrl(string $urlPattern): ?array
    {
        $webhooks = $this->getWebhooks();
        foreach ($webhooks as $wh) {
            if (strpos($wh['url'] ?? '', $urlPattern) !== false) {
                return $wh;
            }
        }
        return null;
    }

    /**
     * Auto-setup: Create or update webhook for this plugin
     *
     * @param string $pluginRoot  Plugin directory (to read ucrm.json for public URL)
     * @param string $secret      Webhook secret (will be set in endpoint header)
     * @param array  $events      Events to subscribe to
     * @return array ['success' => bool, 'message' => string, 'webhook_id' => int|null]
     */
    public function autoSetupWebhook(string $pluginRoot, string $secret, array $events = []): array
    {
        // Get public URL from ucrm.json
        $ucrmConfig = [];
        foreach ([$pluginRoot . '/ucrm.json', $pluginRoot . '/data/ucrm.json'] as $path) {
            if (file_exists($path)) {
                $c = json_decode(file_get_contents($path), true);
                if (is_array($c) && !empty($c)) { $ucrmConfig = $c; break; }
            }
        }
        
        $publicUrl = rtrim($ucrmConfig['ucrmPublicUrl'] ?? '', '/');
        if (empty($publicUrl)) {
            return ['success' => false, 'message' => 'Cannot determine public URL from ucrm.json', 'webhook_id' => null];
        }
        
        // Build the correct webhook URL - must go through public.php
        // UCRM only exposes public.php, not webhook.php directly
        $webhookUrl = $publicUrl . '/_plugins/dishnet-hybrid-telecom/public.php?page=webhook';
        
        // Default events if not specified
        if (empty($events)) {
            $events = [
                'client.add',
                'client.edit',
                'invoice.add',
                'payment.add',
                'service.add',
                'service.suspend',
                'service.suspend_cancel',
                'service.end',
            ];
        }
        
        // Check if webhook already exists (search for our plugin)
        $existing = $this->findWebhookByUrl('dishnet-hybrid-telecom');
        
        if ($existing) {
            // Update existing webhook
            $updated = $this->updateWebhook((int)$existing['id'], [
                'url'                  => $webhookUrl,
                'isActive'             => true,
                'verifySslCertificate' => true,
                'eventTypes'           => $events,
            ]);
            
            if ($updated) {
                return [
                    'success' => true,
                    'message' => "Webhook updated (ID: {$existing['id']})",
                    'webhook_id' => (int)$existing['id'],
                    'url' => $webhookUrl,
                    'events' => $events,
                ];
            } else {
                return [
                    'success' => false,
                    'message' => 'Failed to update webhook: ' . json_encode($this->lastError),
                    'webhook_id' => (int)$existing['id'],
                ];
            }
        } else {
            // Create new webhook
            $created = $this->createWebhook($webhookUrl, $events, true);
            
            if ($created && isset($created['id'])) {
                return [
                    'success' => true,
                    'message' => "Webhook created (ID: {$created['id']})",
                    'webhook_id' => (int)$created['id'],
                    'url' => $webhookUrl,
                    'events' => $events,
                ];
            } else {
                return [
                    'success' => false,
                    'message' => 'Failed to create webhook: ' . json_encode($this->lastError),
                    'webhook_id' => null,
                ];
            }
        }
    }

    // ── CRIT-03 FIX: SSL helpers ──────────────────────────────────────────────
    //
    // By default SSL verification is ENABLED (safe).
    //
    // For UCRM self-signed certs, use ONE of:
    //   A) Set UCRM_CA_CERT=/path/to/ucrm-self-signed.pem   ← recommended
    //   B) Set UCRM_SKIP_SSL_VERIFY=1                        ← only for trusted LAN
    //
    // For external services (WhatsApp, Magma) always use the system CA bundle.
    // Never set UCRM_SKIP_SSL_VERIFY=1 on a public-internet server.

    private static function curlSslVerify(): bool
    {
        return (getenv('UCRM_SKIP_SSL_VERIFY') !== '1');
    }

    private static function caPath(): ?string
    {
        $path = trim((string)(getenv('UCRM_CA_CERT') ?: ''));
        return ($path !== '' && file_exists($path)) ? $path : null;
    }
}
